services:
  db:
    container_name: puntalink-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: puntalink
    volumes:
      - ./data/puntalink.sql:/docker-entrypoint-initdb.d/puntalink.sql
    command: postgres -p 5008
    expose:
      - "5008"
    networks:
      - red_taller_software

  backend:
    container_name: puntalink-backend
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db
    expose:
      - "4008"
    networks:
      - red_taller_software

  frontend:
    container_name: puntalink-frontend
    build: ./frontend
    restart: always
    expose:
      - "3008"
    depends_on:
      - backend
    networks:
      - red_taller_software

networks:
  red_taller_software:
    external: true